[WIP] Put take
marmelab/sg pull request #8
Opened 2016-12-05 08:40 UTC by ThieryMichel

2016-12-12 14:05 UTC, djhi requested changes
Can you split this in at least two pr:
- one for refactoring
- another for the new effects

It's currently hard to review and we shouldn't mix refactoring and new features

2016-12-13 09:30 UTC, djhi commented on README.md
> +Launch another sg generator, but do not wait for it to end. Returning a function that will resolve when the generator is done instead.
s/end. Returning/end, returning/

2016-12-13 09:35 UTC, djhi commented on src/effects/fork.js
> +    const promise = sgImpl(callable, emitter)(...args);
It doesn't check for callable to be a generator as done in [spawn](https://github.com/marmelab/sg/pull/8/files#diff-0e50efdcb840bb7943ea324e136720f6R6) ?

2016-12-13 12:36 UTC, ThieryMichel commented on src/effects/fork.js
> +    const promise = sgImpl(callable, emitter)(...args);
I'ts spawn that should not verify, since sg does it.

2016-12-13 12:59 UTC, djhi approved these changes

2016-12-13 13:00 UTC, merged